spring:
  datasource:
    url: "jdbc:mysql://43.200.44.175:55330/test"
    username: "root"
    password: "Avaya123$"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
