#spring:
#  datasource:
#    url: "jdbc:mariadb://127.0.0.1:3306/simpleBoard"
#    username: "root"
#    password: ""
#    driver-class-name: "org.mariadb.jdbc.Driver"

#mybatis:
#  mapper-locations: query/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
